# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestprvisions():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testprvisions(self):
    self.driver.get("http://127.0.0.1:7860/")
    self.driver.set_window_size(784, 816)
    self.driver.find_element(By.ID, "component-74-button").click()
    self.driver.find_element(By.CSS_SELECTOR, "#component-16 .scroll-hide").click()
    self.driver.find_element(By.CSS_SELECTOR, "#component-16 .scroll-hide").send_keys("casablanca")
    self.driver.find_element(By.CSS_SELECTOR, ".svelte-pjtc3 > .svelte-pjtc3").click()
    self.driver.find_element(By.CSS_SELECTOR, ".svelte-pjtc3 > .svelte-pjtc3").send_keys("3")
    self.driver.find_element(By.ID, "component-25").click()
  
