version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9  # Choisissez une image Docker avec Python 3.9
    working_directory: ~/repo

    steps:
      - checkout

      # Installer les dépendances du projet, y compris pytest et pytest-mock
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install pytest pytest-mock

      # Exécuter les tests unitaires avec pytest
      - run:
          name: Run unit tests
          command: |
            . venv/bin/activate
            pytest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

  
